export enum NotificationType {
    APPOINTMENT_CONFIRMED = 'APPOINTMENT_CONFIRMED',
    APPOINTMENT_CANCELED = 'APPOINTMENT_CANCELED',
    APPOINTMENT_UPDATED = 'APPOINTMENT_UPDATED',
    REMINDER = 'REMINDER',
}
